project '02_Timer.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target '02_Timer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 02_Timer
  
  pod 'SnapKit'

end
